"""Conversations, rubric history, Supabase persistence."""
from rubric_writer.imports import *

def save_message_log(messages, rubric, analysis=None, conversation_id=None):
    """Save conversation to Supabase database.

    If conversation_id is provided, updates the existing conversation.
    Otherwise, inserts a new one.
    """
    project_id = st.session_state.get('current_project_id')
    if not project_id:
        raise ValueError("No project selected. Please select a project first.")

    supabase = st.session_state.get('supabase')
    if not supabase:
        raise ValueError("Database connection not available.")

    # Save to Supabase (update if existing, insert if new)
    conv_id = save_conversation(supabase, project_id, messages, rubric, analysis or "",
                                conversation_id=conversation_id)
    # Invalidate conversations cache so the list refreshes
    cache_key = f"conversations_{project_id}"
    if cache_key in st.session_state:
        del st.session_state[cache_key]
    return conv_id
def _auto_save_conversation():
    """Silently auto-save the current conversation.

    If selected_conversation exists, updates it. Otherwise inserts a new one
    and sets selected_conversation so future saves update the same row.
    Does nothing if there are no messages or no project selected.
    """
    if not st.session_state.get("messages"):
        # print("[AUTO-SAVE] Skipped: no messages")
        return
    if not st.session_state.get("current_project_id"):
        # print("[AUTO-SAVE] Skipped: no project_id")
        pass
        return
    if not st.session_state.get("supabase"):
        # print("[AUTO-SAVE] Skipped: no supabase")
        pass
        return
    try:
        _existing_id = st.session_state.get("selected_conversation")
        # print(f"[AUTO-SAVE] Saving... existing_id={_existing_id}, msg_count={len(st.session_state.messages)}")
        pass
        conv_id = save_message_log(
            st.session_state.messages,
            st.session_state.get("rubric", []),
            st.session_state.get("current_analysis", ""),
            conversation_id=_existing_id,
        )
        if conv_id and conv_id != _existing_id:
            # New insert (or re-insert after stale ID) — record the ID
            st.session_state.selected_conversation = conv_id
            # print(f"[AUTO-SAVE] New conversation saved: {conv_id}")
        elif conv_id:
            # print(f"[AUTO-SAVE] Updated conversation: {conv_id}")
            pass
        else:
            # print("[AUTO-SAVE] save_message_log returned None")
            pass
    except Exception as e:
        # print(f"[AUTO-SAVE] ERROR: {e}")  # Log but don't interrupt the user


        pass
def load_rubric_history(force_reload=False):
    """Load rubric history from Supabase database with caching"""
    project_id = st.session_state.get('current_project_id')
    if not project_id:
        return []

    supabase = st.session_state.get('supabase')
    if not supabase:
        return []

    # Use cached version if available and not forcing reload
    cache_key = f"rubric_history_{project_id}"
    if not force_reload and cache_key in st.session_state:
        return st.session_state[cache_key]

    # Load from database and cache
    history = db_load_rubric_history(supabase, project_id)
    st.session_state[cache_key] = history
    return history


def invalidate_rubric_cache():
    """Clear the rubric history cache to force reload on next access"""
    project_id = st.session_state.get('current_project_id')
    if project_id:
        cache_key = f"rubric_history_{project_id}"
        if cache_key in st.session_state:
            del st.session_state[cache_key]

# Matches dim ids generated by the rubric-config UI's "Add Dimension" button:
# `dim_<13-or-so-digit timestamp>`. We rename these to slug-style ids on save
# so the user-added dims don't stand out from the inferred ones.
_TIMESTAMP_DIM_ID_RE = re.compile(r"^dim_\d{10,}$")
# Acceptable shape for an LLM-generated id.
_GENERATED_ID_RE = re.compile(r"^[a-z][a-z0-9_]{4,39}$")


def _generate_ids_for_user_added_dims(rubric_dict: dict) -> int:
    """When the user clicks Save Version, generate proper slug-style ids for
    any dimensions they manually added via the rubric-config UI (which
    auto-assigns `dim_<timestamp>` ids). Mutates the rubric in place.
    Returns the number of dims renamed.

    Steps:
      1. Find every dim whose id matches `dim_<digits>` AND has at least
         some label or description text (no signal → no rename).
      2. Send all candidates as a batch to the model. Tell it to follow
         the style of the existing slug-style ids in this same rubric
         (e.g. `no_em_dashes`, `quote_connects_to_arc`).
      3. Validate each returned id: snake_case, 5-40 chars, no collision
         with any existing or other newly-generated id in the rubric.
      4. Rename in place. On any LLM failure or invalid output, leave the
         timestamp id untouched -- never block a Save.
    """
    crits = rubric_dict.get("rubric") or []

    # Collect existing ids (for collision-checking) and the candidate list.
    existing_ids: set[str] = set()
    style_examples: list[str] = []
    candidates: list[tuple[int, int, dict]] = []  # (crit_idx, dim_idx, dim)
    for ci, c in enumerate(crits):
        for di, d in enumerate(c.get("dimensions") or []):
            did = (d.get("id") or "").strip()
            if did:
                existing_ids.add(did.lower())
                if not _TIMESTAMP_DIM_ID_RE.match(did):
                    # Use existing inferred ids as in-context style
                    # examples for the LLM. Cap at 8 so prompt stays small.
                    if len(style_examples) < 8:
                        style_examples.append(did)
            if _TIMESTAMP_DIM_ID_RE.match(did or ""):
                label = (d.get("label") or "").strip()
                description = (d.get("description") or "").strip()
                if label or description:
                    candidates.append((ci, di, d))
    if not candidates:
        return 0

    items_for_prompt = []
    for idx, (_ci, _di, d) in enumerate(candidates):
        items_for_prompt.append({
            "idx": idx,
            "criterion": (crits[_ci].get("name") or "").strip(),
            "label": (d.get("label") or "").strip(),
            "description": (d.get("description") or "").strip(),
        })

    items_json = json.dumps(items_for_prompt, ensure_ascii=False, indent=2)
    existing_json = json.dumps(sorted(existing_ids), ensure_ascii=False)
    examples_str = ", ".join(repr(s) for s in style_examples) if style_examples else "(no examples available; use snake_case 5-40 chars)"

    system_prompt = (
        "You generate stable snake_case identifiers for rubric dimensions "
        "based on each dimension's label and description. Each id must be:\n"
        "- snake_case: lowercase letters, digits, underscores\n"
        "- 5-40 characters\n"
        "- start with a letter\n"
        "- semantically reflect the dimension's checkable property\n"
        "- match the style of EXISTING ids in this rubric:\n"
        f"  examples: {examples_str}\n"
        "- not collide with any id in the EXISTING_IDS list\n"
        "- not collide with any id you generate for another dimension in this batch\n"
        "Return ONLY a JSON object mapping each input idx (as string) to its "
        "generated id. No prose, no preamble, no markdown fences."
    )
    user_prompt = (
        f"EXISTING_IDS (must not collide with these): {existing_json}\n\n"
        f"DIMENSIONS:\n{items_json}\n\n"
        f"Return JSON in the form: {{\"0\": \"<id>\", \"1\": \"<id>\", ...}}"
    )

    try:
        from anthropic import Anthropic
        from rubric_writer.config import MODEL_LIGHT
        client = Anthropic()
        resp = client.messages.create(
            model=MODEL_LIGHT,
            max_tokens=2000,
            system=system_prompt,
            messages=[{"role": "user", "content": user_prompt}],
        )
        text = "".join(b.text for b in resp.content if getattr(b, "type", None) == "text")
        m = re.search(r"\{[\s\S]*\}", text or "")
        if not m:
            return 0
        id_map = json.loads(m.group())
        if not isinstance(id_map, dict):
            return 0
    except Exception as e:
        try:
            import logging as _lg
            _lg.getLogger(__name__).warning(
                "[generate dim ids] LLM call failed: %s; keeping timestamp ids", e,
            )
        except Exception:
            pass
        return 0

    renamed = 0
    new_ids: set[str] = set()
    for idx, (_ci, _di, d) in enumerate(candidates):
        proposed = (id_map.get(str(idx)) or id_map.get(idx) or "").strip().lower()
        if not _GENERATED_ID_RE.match(proposed):
            continue
        if proposed in existing_ids or proposed in new_ids:
            continue
        old_id = (d.get("id") or "").lower()
        d["id"] = proposed
        new_ids.add(proposed)
        existing_ids.add(proposed)
        existing_ids.discard(old_id)
        renamed += 1
    return renamed


def save_rubric_history(history):
    """Save rubric history to Supabase database (saves only the latest version).
    Returns the DB-assigned version number, or None on failure.
    """
    project_id = st.session_state.get('current_project_id')
    if not project_id:
        st.error("No project selected. Please select a project first.")
        return None

    supabase = st.session_state.get('supabase')
    if not supabase:
        st.error("Database connection not available.")
        return None

    # Save the latest rubric version
    if history:
        latest = history[-1]
        # If the user manually added any dimensions via the rubric-config UI,
        # those have placeholder ids like `dim_<timestamp>`. Generate proper
        # slug-style ids matching the rest of the rubric BEFORE saving so the
        # DB row has clean ids. Synchronous: the user is already waiting on
        # the Save Version click. Failures are silently tolerated -- the save
        # continues with the timestamp ids if the LLM call fails.
        try:
            n_renamed = _generate_ids_for_user_added_dims(latest)
            if n_renamed:
                import logging as _lg
                _lg.getLogger(__name__).info(
                    "[save_rubric_history] generated slug ids for %d user-added dim(s)",
                    n_renamed,
                )
        except Exception as _e:
            import logging as _lg
            _lg.getLogger(__name__).warning(
                "[save_rubric_history] dim id generation failed: %s", _e,
            )
        result = db_save_rubric_history(supabase, project_id, latest)
        db_version = None
        # Update the version in the local data to match what the DB assigned
        if result and isinstance(result, dict):
            db_version = result["version"]
            latest["version"] = db_version
            latest["id"] = result["id"]
        # Invalidate cache after saving - force reload to get the database-generated ID
        invalidate_rubric_cache()
        # Reload from database to get the proper IDs
        reloaded = load_rubric_history(force_reload=True)
        # Update active_rubric_idx to point to the newly saved version
        if reloaded:
            st.session_state.active_rubric_idx = len(reloaded) - 1
        return db_version
    return None

def next_version_number():
    """Get the next version number for a new rubric"""
    hist = load_rubric_history()
    if not hist:
        return 1
    return max(r.get("version", 1) for r in hist) + 1

def _rubric_to_json_serializable(obj):
    """Return a deep copy of obj with sets converted to lists so it can be JSON-serialized."""
    if isinstance(obj, set):
        return list(obj)
    if isinstance(obj, dict):
        return {k: _rubric_to_json_serializable(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_rubric_to_json_serializable(v) for v in obj]
    return obj


def get_active_rubric():
    """Get the active rubric and its index
    Returns: (full_rubric_dict, active_idx, rubric_history)
    where full_rubric_dict contains both 'version' and 'rubric' keys
    """
    hist = load_rubric_history()
    if not hist:
        return None, None, []

    idx = st.session_state.get("active_rubric_idx")
    if idx is None:
        idx = len(hist) - 1
    if 0 <= idx < len(hist):
        return hist[idx], idx, hist
    return hist[-1] if hist else None, len(hist) - 1 if hist else 0, hist

def _build_conversation_text(messages):
    """Build numbered conversation text from messages for rubric/DP prompts.

    Includes rich structured data from special message types so the model
    sees the full picture: drafts, probes, rubric changes, alignment checks,
    user feedback, accept/revert decisions, etc.
    """
    conversation_text = ""
    msg_num = 1
    for msg in messages:
        role = msg.get('role', 'unknown')
        content = msg.get('content', '')
        # Synthetic changelog messages are context-only — include but don't number
        if msg.get('_synthetic_changelog'):
            conversation_text += f"\n\n[Rubric Version Change]\n{content}"
            continue

        # --- Build enriched content for special message types ---
        enriched = content

        # Probe log: include probe details (why, interpretations, drafts, user choice)
        if msg.get('is_probe_log'):
            pld = msg.get("probe_log_data", {})
            parts = [content]
            if pld.get("variant_a"):
                parts.append(f"\n[Probe Draft — Version A]\n{pld['variant_a']}")
            if pld.get("variant_b"):
                parts.append(f"\n[Probe Draft — Version B]\n{pld['variant_b']}")
            enriched = "\n".join(parts)

        # Criteria classification log: include what was stated/real/hallucinated
        elif msg.get('is_criteria_classification_log'):
            cd = msg.get('classification_data', {})
            parts = [content]
            if cd.get('classifications'):
                parts.append("\n[Criteria Classifications]")
                for _cn, _cat in cd['classifications'].items():
                    _line = f"  - {_cn}: {_cat}"
                    if _cat == "hallucinated" and cd.get('hallucination_reasons', {}).get(_cn):
                        _line += f" — reason: {cd['hallucination_reasons'][_cn]}"
                    parts.append(_line)
            enriched = "\n".join(parts)

        # DP confirmation log: include decision points and rubric mappings
        elif msg.get('is_dp_confirmation_log'):
            dpd = msg.get('dp_data', {})
            parts = [content]
            if dpd.get('decision_points'):
                parts.append("\n[Confirmed Decision Points]")
                for _dp in dpd['decision_points']:
                    parts.append(f"  - Message #{_dp.get('message_number', '?')}: {_dp.get('text', '')}")
                    parts.append(f"    Criterion: {_dp.get('criterion_name', 'unmapped')}")
                    if _dp.get('user_override'):
                        parts.append(f"    User override: {_dp['user_override']}")
            enriched = "\n".join(parts)

        # DP review: include inferred rubric criteria
        elif msg.get('is_dp_review'):
            dpd = msg.get('dp_data', {})
            parts = [content]
            if dpd.get('rubric'):
                parts.append(f"\n[Inferred Rubric v{dpd.get('rubric_version', '?')}]")
                for _rc in dpd['rubric']:
                    parts.append(f"  - {_rc.get('name', 'Unnamed')}: {_rc.get('description', '')}")
            enriched = "\n".join(parts)

        # Inline rephrase: include original/replacement text and instruction
        elif msg.get('is_inline_rephrase'):
            ird = msg.get('inline_rephrase_data', {})
            parts = [content]
            if ird:
                parts.append(f"\n[Inline Rephrase]")
                parts.append(f"  Original text: {ird.get('original_text', '')}")
                parts.append(f"  Replacement: {ird.get('replacement_text', '')}")
                parts.append(f"  Instruction: {ird.get('instruction', '')}")
            enriched = "\n".join(parts)

        # Format based on role
        if role == 'user':
            conversation_text += f"\n\n[Message #{msg_num}] USER:\n{enriched}"
            msg_num += 1
        elif role == 'assistant':
            conversation_text += f"\n\n[Message #{msg_num}] ASSISTANT:\n{enriched}"
            msg_num += 1
        elif role == 'system':
            conversation_text += f"\n\n[Message #{msg_num}] SYSTEM:\n{enriched}"
            msg_num += 1
    return conversation_text
def load_conversations(force_reload=False):
    """Load all conversations from Supabase database with caching"""
    project_id = st.session_state.get('current_project_id')
    if not project_id:
        return []

    supabase = st.session_state.get('supabase')
    if not supabase:
        return []

    cache_key = f"conversations_{project_id}"
    if not force_reload and cache_key in st.session_state:
        return st.session_state[cache_key]

    conversations = db_load_conversations(supabase, project_id)
    # Add filename field for compatibility with existing code
    for conv in conversations:
        conv["filename"] = conv["id"]
    st.session_state[cache_key] = conversations
    return conversations

def load_conversation_data(conversation_id):
    """Load conversation data from Supabase database"""
    supabase = st.session_state.get('supabase')
    if not supabase:
        return None

    return load_conversation_by_id(supabase, conversation_id)

def get_available_projects():
    """Get list of available projects for the current user from Supabase"""
    user_id = st.session_state.get('auth_username')
    if not user_id:
        return []

    supabase = st.session_state.get('supabase')
    if not supabase:
        return []

    projects = get_user_projects(supabase, user_id)
    return projects  # Returns list of dicts with 'id', 'name', etc.

def create_new_project(project_name):
    """Create a new project in Supabase database"""
    import string
    valid_chars = string.ascii_letters + string.digits + '-_ '
    if not all(c in valid_chars for c in project_name):
        return False, "Project name can only contain letters, numbers, hyphens, underscores, and spaces"

    user_id = st.session_state.get('auth_username')
    if not user_id:
        return False, "Not authenticated"

    supabase = st.session_state.get('supabase')
    if not supabase:
        return False, "Database connection not available"

    success, message, project_id = db_create_project(supabase, user_id, project_name)
    return success, message, project_id
